version: '3'
services:
  testapp:
    build: .
    container_name: testapp
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3000:3000'
    expose: 
      - '3000'
    command: [ "node", "index.js"]
