name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Secrets
        run: |
          echo "VPS_HOST: ${{ secrets.SSH_HOST }}"
          echo "VPS_USERNAME: ${{ secrets.SSH_USERNAME }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS , host ${{ secrets.SSH_HOST }} , username ${{ secrets.SSH_USERNAME }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/app/simpleapp

            # Check if the directory is a Git repository before running Git commands
            if [ -d ".git" ]; then
              git pull origin main
              git status
            else
              echo "Error: Not a Git repository. Initializing a new Git repository."
              git init
              git remote add origin <your-repository-url>
              git fetch origin main
              git checkout -b main --track origin/main
            fi

            # Install Node.js and npm (if not already installed)
            if ! command -v npm &> /dev/null; then
              echo "Error: npm not found. Installing Node.js and npm."
              sudo apt-get update
              sudo apt-get install -y nodejs npm
            fi

            git pull origin main
            git status
            npm install
